### PR TITLE
Fix Keystone v3 support

### PR DESCRIPTION
**Pull request by voelzmo**
Bug: https://github.com/cloudfoundry/bosh/issues/939

* When using the Keystone V3 API, the `openstack_tenant` parameter is renamed to `openstack_project_name` in fog
* Have different validation strategies for the corresponding API versions: V2 requires a different set of properties than V3

required for V3 to work:
* Change bosh director to accept the `project` parameter
* Update bosh to use fog >=1.34.0 to include fixes necessary for V3 API support
* Adapt `bosh_openstack_cpi.gemspec` to remove lock-down of `fog-aws`, update to fog >= 1.34.0 and `vendor_gems` in here so the new gems get pulled in

### CODE REVIEW

**Comment by voelzmo** [comment]
Updating the CPI to fog 1.34.0 with https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/pull/11

**Comment by cppforlife** [comment]
> Move initialization of volume service to initialization of the CPI. Now similar to the other two services, image and compute

That was done on purpose. There is a use case for not using volume service at all which means it's not connectable. We should probably add a tests that states that. Also it's generally a good practice to not do any real work in #initialize.

**Comment by voelzmo** [comment]
@cppforlife thanks for giving me some more context on that, I wasn't aware that this lazy initialization was done on purpose. I'll take some time to rework this accordingly.

The supported use case is that no persistent disks are used and therefore `create_disk` is never called?

**Comment by voelzmo** [comment]
Added commit and adapted description of the PR to reflect that initialization of the volume service is no longer moved.

**Comment by cppforlife** [comment]
@voelzmo just noticed, what's with non-standard indent? rubymine?

**Comment by voelzmo** [comment]
@cppforlife I'm using rubymine to format, yes. If you prefer a different format, we should find a way to sync our settings, e.g. by referencing settings or even checking them in.

However, looking at the file - for example comparing [line 582](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L582) and [line 587](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L587) I think that formatting is not very consistent across the file right now...

**Comment by loewenstein** [comment]
I personally never used http://editorconfig.org/, but aparently [quite some OS projects](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig) use it.

The set of formatting options is limited, but it does contain indention. It is supported by a lot of editors, some requiring additional plugins.

**Comment by voelzmo** [comment]
Pulled in with https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/commit/570d207d009bcb3a847347c787442ba788f74d0c

**Pull request closed without merging**
