### PR TITLE
Enable S3 blobstore support

### PR DESCRIPTION
**Pull request by frodenas**
Add support for S3 compatible blobstores (like OpenStack Swift with the S3 API enabled).

### CODE REVIEW

**Comment by frodenas** [comment]
@jerenkrantz FYI

**Comment by JamesClonk** [comment]
:+1: 

I'd like that very much. I'm currently unable to setup the BOSH director with bosh-init to use an external S3 blobstore as both the director and the cpi template use the same blobstore property, but the cpi template only knows about `local` or `simple`, so I run into a conflict there with bosh director template.

**Comment by jerenkrantz** [comment]
I think that this patch is good - the director can upload items into the blobstore.

Due to bloomberg/chef-bcpc#596, I can't upload releases/packages greater than the specified multipart threshold into `radosgw`, but that appears to be an entirely separate issue.  (IOW, the client is doing the right thing; but, the server isn't.)

Thanks!

**Comment by cppforlife** [comment]
Merged: https://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?version=8

**Comment by frodenas** [comment]
Thanks @cppforlife!

**Pull request closed without merging**
