### PR TITLE
Test if string is not null nor empty

### PR DESCRIPTION
**Pull request by shoudusse**
Fix https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/issues/62

### CODE REVIEW

**Comment by voelzmo** [comment]
Hey @shoudusse, thanks for the PR. Would you mind also adding a testcase similar to the one [testing for `nil` as `floating_ip.port`](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/spec/unit/floating_ip_spec.rb#L104)? Thanks!

**Comment by voelzmo** [comment]
ping @shoudusse: any chance you're adding a test to this change?

**Comment by gberche-orange** [comment]
@voelzmo sorry for the delay in implementing the tests, we're still ramping up with ruby syntax.

The updated PR extracted the logic into a distinct method and added test coverage. We hope this respects the cpi code style. 

Thanks in advance,

Sylvain & Guillaume.

**Comment by voelzmo** [comment]
@gberche-orange no worries, I was just wondering if we should pick it up or if you were planning to do it :)

Thanks for adding tests, we will look at it and pull it in!

**Comment by Kiemes** [comment]
Merged with slight style modification. https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/commit/a7acc14d467979b75ed7252e5f8845f15308b4e7

@shoudusse thanks again

**Comment by gberche-orange** [comment]
great, thanks @Kiemes

**Pull request closed without merging**
