### PR TITLE
Add terraform outputs for manual ip address for lifecycle tests

### PR DESCRIPTION
**Pull request by ljfranklin**
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

### CODE REVIEW

**Comment by ljfranklin** [comment]
If you wanted, you could add a similar set of IP address outputs for the BATS networks. For the AWS CPI, we convert the terraform output to JSON files and interpolate that into a [director manifest](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/bf0d4d1d47511aa4e78f2e43dc1a6c111a1c8fb1/ci/tasks/prepare-director.sh#L89-L99). By using the [terraform-resource](https://github.com/ljfranklin/terraform-resource), we can consume the Terraform output directly in Concourse without pasting IPs into LastPass first.

We the manage these JSON files with the [pool-resource](https://github.com/concourse/pool-resource). A director lock file looks like this:

```
{
  "PublicCIDR":"10.0.0.0/16",
  "PublicSubnetID":"subnet-XXXXXXX",
  "ReservedRange":"10.0.0.2-10.0.0.9",
  "StaticRange":"10.0.0.10-10.0.0.30",
  "DirectorPrivateIP":"10.0.0.6",
  ...
}
```

The deploy director jobs can then claim a lock file to do the deployment, run tests, then release the lock back into the pool. Allows for more jobs to run in parallel and humans can claim a lock to run manual tests without stepping on CI's toes.

**Comment by friegger** [comment]
@ljfranklin Fyi, integrating terraform in our pipeline is under consideration, you can follow [here](https://www.pivotaltracker.com/story/show/119565681). Cheers to the CPI team!

**Comment by voelzmo** [comment]
@ljfranklin Does that mean you keep directors for more than one test run? Or why is it that you keep a pool of those settings instead of creating it on every run from scratch?

**Comment by ljfranklin** [comment]
@voelzmo no we don't keep our directors around. Creating pools of environments is a more general approach for envs that need a dependency like a director or CF installed prior to testing, but I agree it doesn't give much benefit when testing a CPI.

The real benefit of the Terraform stuff is going directly from Terraform Outputs to a BOSH manifest. Creating an environment then copy-pasting properties like static and reserved ranges into LastPass is the main thing to avoid.

**Comment by voelzmo** [comment]
@ljfranklin avoiding copy-paste makes perfect sense to me. That's why I'm thinking about tearing the whole OpenStack project down after a run and setting it up in the beginning from scratch. That way you also ensure that the templates stay up-to-date :)

**Pull request merged**
