### PR TITLE
multi CPI support

### PR DESCRIPTION
**Pull request by MatthiasWinzeler**
This PR adds support for the recently merged [multi cpi feature in bosh](https://github.com/cloudfoundry/bosh/pull/1471). To support this, each CPI must respect configuration that might be provided dynamically in the `context` of each CPI call.

What's in the changeset:

- The `bosh_cpi` and `bosh_common` were updated to the version that passes `context` to the cpi lambda
- We intentionally **merge** (and not overwrite) the openstack properties from the director config with those provided in `context`, so that the default properties from the bosh release are taken into account (and the cpi config does not have to set them)
- Refactoring the cpi lambda to its own class (to be able to spec it)

Unit tests are passing. Since I was not able to run the integration tests on our environment (we still use keystone v2),  @voelzmo [will provide a pipeline that runs them](https://www.pivotaltracker.com/story/show/134691085). Thanks!

### CODE REVIEW

**Comment by ljfranklin** [comment]
@MatthiasWinzeler The BOSH team ended up removing the nested `context.openstack` key in favor of passing all keys at the top-level of `context`. Could you apply the following patch to your PR? Otherwise this PR looks in-line with the changes we've made in AWS and vSphere CPI, nice work! cc @voelzmo to merge

Patch:
```diff
diff --git a/src/bosh_openstack_cpi/lib/cloud/openstack/cpi_lambda.rb b/src/bosh_openstack_cpi/lib/cloud/openstack/cpi_lambda.rb
index 61bed34..70102bc 100644
--- a/src/bosh_openstack_cpi/lib/cloud/openstack/cpi_lambda.rb
+++ b/src/bosh_openstack_cpi/lib/cloud/openstack/cpi_lambda.rb
@@ -18,19 +18,17 @@ module Bosh::OpenStackCloud
         end
 
         # allow openstack config to be overwritten dynamically by context
-        if context['openstack']
-          cloud_properties['openstack'].merge!(context['openstack'])
+        cloud_properties['openstack'].merge!(context)
 
-          # write ca cert to disk if given in context
-          connection_options = cloud_properties['openstack']['connection_options']
-          if connection_options && (ca_cert = connection_options.delete('ca_cert'))
-            File.write(ca_cert_from_context, ca_cert)
-            connection_options['ssl_ca_file'] = ca_cert_from_context
-          end
+        # write ca cert to disk if given in context
+        connection_options = cloud_properties['openstack']['connection_options']
+        if connection_options && (ca_cert = connection_options.delete('ca_cert'))
+          File.write(ca_cert_from_context, ca_cert)
+          connection_options['ssl_ca_file'] = ca_cert_from_context
         end
 
         Bosh::Clouds::Openstack.new(cloud_properties)
       end
     end
   end
-end
\ No newline at end of file
+end
diff --git a/src/bosh_openstack_cpi/spec/unit/cpi_lambda_spec.rb b/src/bosh_openstack_cpi/spec/unit/cpi_lambda_spec.rb
index 8be4344..d7ae0a0 100644
--- a/src/bosh_openstack_cpi/spec/unit/cpi_lambda_spec.rb
+++ b/src/bosh_openstack_cpi/spec/unit/cpi_lambda_spec.rb
@@ -47,10 +47,8 @@ describe Bosh::OpenStackCloud::CpiLambda do
     context 'if openstack properties are provided in the context' do
       it 'merges the openstack properties' do
         context = {
-            'openstack' => {
-                'newkey' => 'newvalue',
-                'newkey2' => 'newvalue2',
-            }
+          'newkey' => 'newvalue',
+          'newkey2' => 'newvalue2',
         }
 
         expect(Bosh::Clouds::Openstack).to receive(:new).with({'openstack' => { 'key1' => 'value1',
@@ -65,10 +63,8 @@ describe Bosh::OpenStackCloud::CpiLambda do
         ca_file = Tempfile.new('ca_cert')
 
         context = {
-            'openstack' => {
-                'newkey' => 'newvalue',
-                'connection_options' => {'ca_cert' => 'xyz'}
-            }
+          'newkey' => 'newvalue',
+          'connection_options' => {'ca_cert' => 'xyz'}
         }
 
         expect(Bosh::Clouds::Openstack).to receive(:new).with({'openstack' => { 'newkey' => 'newvalue',
@@ -82,4 +78,4 @@ describe Bosh::OpenStackCloud::CpiLambda do
       end
     end
   end
-end
\ No newline at end of file
+end
```

**Comment by MatthiasWinzeler** [comment]
@ljfranklin : Thanks for the input. I applied the patch.

**Comment by cppforlife** [comment]
@voelzmo i think this PR is ready to be reviewed/merged by your team.

**Comment by voelzmo** [comment]
@MatthiasWinzeler @cppforlife @ljfranklin Thanks for the PR and review. We'll setup a pipeline and look at the PR soon.

**Comment by friegger** [comment]
@MatthiasWinzeler Thank you for the contribution!

**Pull request merged**
