### PR TITLE
Don't sub shell and use set -e -x in packaging scripts

### PR DESCRIPTION
**Pull request by friegger**
The original behavior would exit before printing out the human readable
error.

[#119500797](https://www.pivotaltracker.com/story/show/119500797)

### CODE REVIEW

**Comment by friegger** [comment]
Do not merge, this is still under discussion.

**Comment by friegger** [comment]
This align the packaging scripts of the CPIs.

**Comment by cheeseblubber** [comment]
Don't merge this yet we are not done with the story yet there may be more changes https://www.pivotaltracker.com/story/show/119609491

**Comment by voelzmo** [comment]
@cheeseblubber are you talking about this PR or the one I already merged today (https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/pull/37)? :D

**Pull request merged**
