### PR TITLE
DoNotMerge, openlab integration test

### PR DESCRIPTION
**Pull request by animationzl**

### CODE REVIEW

**Comment by animationzl** [comment]
recheck stable/newton

**Comment by voelzmo** [comment]
Hey @animationzl,

Thanks for the PR. I was trying to find the test logs under the link, but it seems the symlink you create with `ln -s /root/.cf-openstack-validator/logs /home/zuul/workspace/cpi-logs` either is ignored, or the copy job only copies everything under `/home/zuul/workspace/logs`. Either way, I'm not finding the log output of our test run.

**Comment by animationzl** [comment]
Dear voelzmo,
thanks for your feedback, will add a task to collect the cpi-logs

**Comment by animationzl** [comment]
recheck stable/newton

**Comment by animationzl** [comment]
Hey @voelzmo 
now please check the cpi logs in 'logs/cpi-logs' directory under the link, such as http://logs.openlabtesting.org/logs/40/140/4be63fd60b15a60277d99435baaf576eca262a46/recheck-newton/bosh-openstack-cpi-release-acceptance-test-newton/e51046f/logs/cpi-logs/

**Comment by voelzmo** [comment]
Thanks, I can see the logs now!

**Comment by voelzmo** [comment]
I'm closing this one as we've merged the PR for the job configuration. Thanks!

**Pull request closed without merging**
