### PR TITLE
Enable ppc64le support

### PR DESCRIPTION
**Pull request by hashmap**
- enable nokogiri build on POWER Linux using system libraries
- enable ruby-yaml build by specifying platform, since config.guess and config.sub files in the package are outdated

### CODE REVIEW

**Comment by voelzmo** [comment]
Hey @hashmap thanks for the PR. 

I don't think we should download things in the `packaging` script as you do using `apt-get` here. I guess we have to either package them or make sure they are already on the stemcell.

In some environments the VMs compiling/packaging might not even have internet connectivity at all.

**Comment by hashmap** [comment]
@voelzmo I have the same concern and we will add those packages to power stemcell. However on power we use only bosh-init to insall bosh and I'm not an expert in bosh-init but I didn't see that change in a stemcell helped to fix this issue. I assume it uses a local chroot env?

**Comment by hashmap** [comment]
Hey @voelzmo we had a discussion with @cppforlife, he suggested to check if those debs are installed, if not print out a message and stop the deployment, user should install them manually. Another option he suggested is to bump nokogiri, 1.7 can be installed on power without any additional steps. Any concern reg bumping?

**Comment by voelzmo** [comment]
I think you can go ahead an just bump nokogiri. This sounds like the better alternative than checking for packages to be installed an fail otherwise.

BTW: Do we have the same problems for compiling core bosh as well?

**Comment by hashmap** [comment]
cool, will test it and then update this pr. 
we have this problem with installing bosh_cli, would be nice to bump there too.

**Comment by voelzmo** [comment]
Thanks, @hashmap, we'll pull this in and make a release soon.
It seems, however, that the libyaml maintainers should update their config.guess with the newest version from http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD

Could you please open an issue in their tracker and check that they do it? We could then get rid of the ugly `if-then-else` during the installation.

Thanks!

**Comment by voelzmo** [comment]
Released with v17.

**Pull request merged**
