### PR TITLE
Implement `calculate_vm_cloud_properties` CPI method

### PR DESCRIPTION
**Pull request by ljfranklin**
- This method will allow BOSH to make cpu, ram, and ephemeral_disk first class VM properties rather than IaaS-specific cloud_props
  - E.g. `vm_types.cloud_properties.flavor` can now be replaced with `vm_types.{cpu,ram,ephemeral_disk}` in your manifest
  - Allows for greater manifest portability between IaaS
- BOSH will take the result of calculate_vm_cloud_properties, merge it with various manifest cloud_properties (e.g. vm_type), then pass it all to create_vm
- Only tricky bit was handling of ephemeral disks, see "In the case where no ephemeral disk is large enough" comment in code

[#126023557](https://www.pivotaltracker.com/story/show/126023557)

Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

### CODE REVIEW

**Comment by cdutra** [comment]
Hello @voelzmo and SAP gang! While there's no real rush to merge this as the `calculate_vm_cloud_properties` work has not been completed on BOSH Core's side, we'd like to merge this while we still have context. Any concerns about merging this? Would you like us to rebase off of master? We noticed a merge branch in progress here: 11b73f793a6148bd0fd8857dca914892e98950e5.

**Comment by voelzmo** [comment]
Hey @cdutra we're in the process of rebasing and merging this in. I guess if there's something to do from your side, we'll ping you. Stay tuned! :)

**Comment by friegger** [comment]
@cdutra We merged locally to run the integration tests against an OpenStack on our side. Today we had a deeper look at the code and have no complains. Thanks for the work!

**Comment by Kiemes** [comment]
@cdutra @ljfranklin just for your information.We changed the behavior a bit regarding boot_from_volume. It is required to use a flavor with ephemeral disk size 0 when using boot_from_volume. Otherwise ephemeral disk is attached from hypervisor-local storage.
https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/commit/e5b0f62d0063b95473720536715c53c551227c92

**Pull request merged**
